# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'PolitiKnow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'AWSMobileClient', '~> 2.6.6'
    # other pods
end
 
 # Pods for PolitiKnow

  target 'PolitiKnowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolitiKnowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
