# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'PolitiKnow' do
     pod 'AWSMobileClient', '~> 2.6.6'
     pod 'AWSDynamoDB', '~> 2.6.13'
    # other pods
end
 
 # Pods for PolitiKnow

  target 'PolitiKnowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolitiKnowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

